# A program to display Green Eggs and Ham (v2)
def displayChorus():
    print()
    print("I do not like green eggs and ham.")
    print("I do not like them Sam-I-am.")
    print()

displayChorus()    
print("I do not like them here or there.")
print("I do not like them anywhere.")
print("I do not like them in a house")
print("I do not like them with  a mouse")
displayChorus()
print("I do not like them in a box")
print("I do not like them with a fox")
print("I will not eat them in the rain.")
print("I will not eat them on a train")
displayChorus()
